CREATE TABLE Livreur_Task (
	ID INT PRIMARY KEY IDENTITY(1,1),	
	Title NVARCHAR(250) NOT NULL,
	StartHour INT NOT NULL,
	EndHour INT NOT NULL,
	Description NVARCHAR(MAX) NULL,
	DayID INT NOT NULL FOREIGN KEY REFERENCES Livreur_Schedule(ID) ON DELETE CASCADE,
)
