CREATE TABLE Vehicle (
    ID INT PRIMARY KEY IDENTITY(1,1),
	Matricule NVARCHAR(255) UNIQUE NOT NULL,
	Type INT NOT NULL FOREIGN KEY REFERENCES Collection_items(Id),
	Model NVARCHAR(255) NULL,
	Img INT NULL FOREIGN KEY REFERENCES DB_Files(ID),
	Permis INT NULL FOREIGN KEY REFERENCES DB_Files(ID),
	Assurance INT NULL FOREIGN KEY REFERENCES DB_Files(ID),
	)