CREATE TABLE [User] (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    AccountId VARCHAR(20) UNIQUE NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
	PhoneNumber VARCHAR(25) UNIQUE NOT NULL,
    PasswordHash VARCHAR(MAX) NOT NULL,	
	Validated BIT NOT NULL DEFAULT 0,
    StatusId INT NOT NULL FOREIGN KEY REFERENCES UserStatus(Id),
    RoleId INT NOT NULL FOREIGN KEY REFERENCES Role(Id)
);