Create TABLE Horaire (
	ID INT PRIMARY KEY IDENTITY(1,1),
	MONDAY NVARCHAR(255) NULL,
	TUESDAY NVARCHAR(255) NULL,
	WEDNESDAY NVARCHAR(255) NULL,
	THURSDAY NVARCHAR(255) NULL,
	FRIDAY NVARCHAR(255) NULL,
	SATURDAY NVARCHAR(255) NULL,
	SANDAY NVARCHAR(255) NULL,
)

CREATE TABLE Livreur (
	ID NVARCHAR(50) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Lastname NVARCHAR(255) NOT NULL,
	CreationDate DATETIME NOT NULL, 
	Email NVARCHAR(255) UNIQUE NOT NULL,
	Phone NVARCHAR(25) UNIQUE NOT NULL,
	Adresse NVARCHAR(255) NULL,
	Postal NVARCHAR(255) NULL,
	City NVARCHAR(100) NULL,
	Country NVARCHAR(100) NULL,
	Img INT NULL FOREIGN KEY REFERENCES DB_Files(ID),
	Vehicle INT NULL FOREIGN KEY REFERENCES Vehicle(ID),
	Horaire INT NULL FOREIGN KEY REFERENCES Horaire(ID),
	StatusID INT NOT NULL FOREIGN KEY REFERENCES UserStatus(Id),
)

CREATE TABLE LivreursLangues (
    LivreurId NVARCHAR(50) NOT NULL,
    CollectionItemId INT NOT NULL,
    
    PRIMARY KEY (LivreurId, CollectionItemId),
    
    FOREIGN KEY (LivreurId) REFERENCES Livreur(ID)
        ON DELETE CASCADE,
        
    FOREIGN KEY (CollectionItemId) REFERENCES Collection_Items(Id)
        ON DELETE CASCADE
);


