CREATE TABLE Entrep_Sites (
	ID INT PRIMARY KEY IDENTITY(1,1),
	TypeID INT NOT NULL FOREIGN KEY REFERENCES Collection_Items(ID),
	DisponibilityID INT NOT NULL FOREIGN KEY REFERENCES Collection_Items(ID),
	Adresse NVARCHAR(MAX) NOT NULL,
	CityID INT NOT NULL FOREIGN KEY REFERENCES Cities_Countries(ID),
	Email NVARCHAR(255) NOT NULL,
	Phone NVARCHAR(255) UNIQUE NOT NULL,
	Destinateur BIT NOT NULL DEFAULT 0,
	EntrepriseID NVARCHAR(25) NOT NULL
)
